import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Nav from "@/components/nav/nav";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${openSans.className}  bg-slate-200`}>
        <header>
          <Header />
          <Nav />
        </header>
        <main className="lg:px-36 pb-10"> {children}</main>
      </body>
    </html>
  );
}
